---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: openshift-runners-vault-tec
spec:
  # Using "HorizontalRunnerAutoscaler"
  # replicas: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      group: OpenShift
      labels:
        - docker,openshift
      organization: vault-tec
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "250m"
          memory: "500Mi"
      image: ghcr.io/ocpdude/docker-runner:latest
      containers:
        - name: docker
          volumeMounts:
            - mountPath: /etc/docker/daemon.json
              name: daemon-json
              subPath: daemon.json
      volumes:
        - name: daemon-json
          configMap:
            name: daemon-json
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: vault-tec-runner-autoscaler
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: openshift-runners-vault-tec
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.25'
      scaleUpFactor: '2'
      scaleDownFactor: '0.5'