apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: scc-podman-runner
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      serviceAccountName: github-arc-sa
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      dockerEnabled: false # << DISABLE DOCKERD
      group: OpenShift
      labels:
        - podman
      organization: ocpdude
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "250m"
          memory: "250Mi"
      image: registry.redcloud.land/actions-runner-podman:1.11
