---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-arc-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-github-arc-scc
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["github-arc-scc"]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-github-arc-scc
subjects:
  - kind: ServiceAccount
    name: github-arc-sa
roleRef:
  kind: ClusterRole
  name: use-github-arc-scc
  apiGroup: rbac.authorization.k8s.io