kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: github-arc-scc
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange 
  uidRangeMin: 1000
  uidRangeMax: 2000
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: MustRunAs 
  ranges:
  - min: 1000
    max: 2000
supplementalGroups:
  type: MustRunAs 
  ranges:
  - min: 1000
    max: 2000