---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: openshift-podman-runner
spec:
  # Using HorizontalRunnerAutoscaler? Update replica's to 0
  replicas: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      # Assign runner group
      dockerEnabled: false # << DISABLE DOCKERD
      group: OpenShift
      labels:
        - podman
      organization: ocpdude
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "250m"
          memory: "250Mi"
      image: ghcr.io/ocpdude/podman-runner:latest