name: Actions Custom Runner

on:
  push:
    branches:
    - main
    paths:
    - './builds/actions-custom-runner/Dockerfile'
  workflow_dispatch:
   
env:
  REGISTRY: ghcr.io
  FILTER_REGEX_EXCLUDE: ./builds/podman/.*
  
jobs:

  docker-linter:
    uses: ocpdude/reusable/.github/workflows/linter.yaml@main
    with:
      language: hadolint

  build_push:
    needs: [ docker-linter ]
    name: Build image
    runs-on: [ ubuntu-latest ] 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Context
      id: buildx-context
      run: |
        docker context create builders || docker context use builders
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        endpoint: builders

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Registries
      uses: docker/build-push-action@v3
      with:
        context: ./builds/actions-custom-runner/
        push: true
        tags: |
          ${{env.REGISTRY}}/ocpdude/actions-custom-runner:${{github.run_number}}
          ${{env.REGISTRY}}/ocpdude/actions-custom-runner:latest
 
  check_quality:
    needs: build_push
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Scanning Image
      continue-on-error: true
      uses: azure/container-scan@v0
      with:
        image-name: ${{env.REGISTRY}}/ocpdude/actions-custom-runner:latest
        run-quality-checks: true
