name: Podman Custom Runner

on:
  push:
    branches:
    - main
    paths:
    - '.openshift/builds/podman/Dockerfile'
  workflow_dispatch:
   
env:
  REGISTRY: ghcr.io 
  FILTER_REGEX_EXCLUDE: ./builds/actions-custom-runner/.*
  
jobs:

  docker-linter:
    uses: ocpdude/reusable/.github/workflows/linter.yaml@main
    with:
      language: hadolint

  security-checks:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    needs: [ docker-linter ]
    steps:
    - uses: actions/checkout@v4
    - name: Build the test image
      run: docker build . --file ./openshift/build/podman/Dockerfile --tag localbuild/testimage:latest
    - name: Grype scan the test image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "localbuild/testimage:latest"
        fail-build: false
        severity-cutoff: critical
    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
    
  build_push:
    needs: [ docker-linter, security-checks ]
    name: Build image
    runs-on: [ ubuntu-latest ] 
    steps:
    - name: Get the date
      id: date
      run: echo "::set-output name=date::$(date +'%m%d')"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Context
      id: buildx-context
      run: |
        docker context create builders || docker context use builders
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        endpoint: builder
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to Registries
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./builds/podman/
        tags: |
          ${{env.REGISTRY}}/ocpdude/actions-runner-controller/podman-runner:${{ steps.date.outputs.date }}
          ${{env.REGISTRY}}/ocpdude/actions-runner-controller/podman-runner:latest
        platforms: linux/amd64